openapi: 3.0.1
info:
  title: Catalog
  version: 0.0.0
servers:
- url: "{server}:{port}/catalog"
  variables:
    server:
      default: http://localhost
    port:
      default: "9090"
paths:
  /addCatalog:
    post:
      operationId: postAddcatalog
      requestBody:
        content:
          '*/*':
            schema:
              description: Any type of entity body
      responses:
        "500":
          description: Found unexpected output
          content:
            text/plain:
              schema:
                type: string
  /updateCatalog:
    put:
      operationId: putUpdatecatalog
      requestBody:
        content:
          '*/*':
            schema:
              description: Any type of entity body
      responses:
        "500":
          description: Found unexpected output
          content:
            text/plain:
              schema:
                type: string
  /deleteCatalog:
    delete:
      operationId: deleteDeletecatalog
      requestBody:
        content:
          '*/*':
            schema:
              description: Any type of entity body
      responses:
        "500":
          description: Found unexpected output
          content:
            text/plain:
              schema:
                type: string
components: {}
